# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, defaults to 'filename'; if not specified, the 'utc' timezone
# will be used.
# timezone = Europe/London

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file in the same process
# instead of spawning a subprocess.
# fork_per_engine = false

# set to 'true' to force the usage of 'synchronize_session' as
# SYNC in all revisions.
# synchronize_session = false

# set to 'true' to make all UPDATE and DELETE statements involved
# in the migration to have a batch size of 1000.
# batch_size = 1000

# set to 'true' to enable logging all revisions when applying
# migrations.
# log_revisions = false

# set to 'true' to enable version comparison when
# upgrading.
# version_comparison = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

# sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# after generating new migration scripts.
#   format using pkg_resources:entry_points notation or plain paths.

# logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
formatter = generic
args = (sys.stderr,)

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S